# Generated by Django 5.1.5 on 2025-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustercapacity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='clusterprovider',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='node',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='reserveplan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at'),
        ),
    ]
