# Generated by Django 5.1.4 on 2025-01-14 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterProvider',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(default='no description')),
                ('provider_type', models.CharField(max_length=64, unique=True)),
                ('cluster_cpu_capacity', models.IntegerField(default=0)),
                ('cluster_gpu_capacity', models.IntegerField(default=0)),
                ('cluster_mem_capacity', models.IntegerField(default=0)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cloud.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
