# Generated by Django 5.1.4 on 2025-01-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_clusterprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterprovider',
            name='provider_type',
            field=models.CharField(choices=[('k8s', 'Kubernetes')], default='k8s', max_length=64, unique=True),
        ),
    ]
