# Generated by Django 5.1.5 on 2025-01-20 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_clustercapacity_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQueue',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quota', models.ForeignKey(db_comment='The quota that this queue belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='cloud.quota')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
