# Generated by Django 5.1.5 on 2025-01-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_taskqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskqueue',
            name='cpu_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='gpu_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='mem_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='name',
            field=models.CharField(default='default', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskqueue',
            name='queue_selector',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
