# Generated by Django 5.1.4 on 2025-01-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_alter_clusterprovider_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterprovider',
            name='cluster_auth',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterprovider',
            name='cluster_endpoint',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
