# Generated by Django 5.1.4 on 2025-01-14 03:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_clusterprovider_cluster_auth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterprovider',
            name='cluster_cpu_capacity',
        ),
        migrations.RemoveField(
            model_name='clusterprovider',
            name='cluster_gpu_capacity',
        ),
        migrations.RemoveField(
            model_name='clusterprovider',
            name='cluster_mem_capacity',
        ),
        migrations.CreateModel(
            name='ClusterCapacity',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster_cpu_capacity', models.IntegerField(default=0)),
                ('cluster_gpu_capacity', models.IntegerField(default=0)),
                ('cluster_mem_capacity', models.IntegerField(default=0)),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cloud.clusterprovider')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClusterResourceQuota',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_quota', to='cloud.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
