# Generated by Django 5.1.5 on 2025-01-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_alter_taskqueue_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='cluster_provider',
        ),
    ]
