# Generated by Django 5.1.4 on 2025-01-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_remove_clusterprovider_cluster_cpu_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clustercapacity',
            name='cluster',
        ),
        migrations.AddField(
            model_name='clustercapacity',
            name='zone',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='cloud.zone'),
            preserve_default=False,
        ),
    ]
