# Generated by Django 5.1.5 on 2025-01-21 06:49

import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_remove_node_cluster_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneCapacityStatic',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_capacity', models.IntegerField(default=0)),
                ('gpu_capacity', models.IntegerField(default=0)),
                ('mem_capacity', models.IntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_static', to='cloud.zone')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
