# Generated by Django 5.1.4 on 2025-01-14 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_remove_clustercapacity_cluster_clustercapacity_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clustercapacity',
            name='zone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='cloud.zone'),
        ),
    ]
