# Generated by Django 5.1.5 on 2025-01-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_zonecapacitystatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonecapacitystatic',
            name='audited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
