# Generated by Django 5.1.4 on 2025-01-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_alter_clustercapacity_zone'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterresourcequota',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resource_quota', to='project.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clusterresourcequota',
            name='quota_cpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clusterresourcequota',
            name='quota_gpu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clusterresourcequota',
            name='quota_mem',
            field=models.IntegerField(default=0),
        ),
    ]
