# Generated by Django 5.1.4 on 2025-01-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_clusterresourcequota_project_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClusterResourceQuota',
            new_name='Quota',
        ),
    ]
