# Generated by Django 5.1.5 on 2025-01-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_zonecapacitystatic_audited_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusterCapacity',
        ),
    ]
