# Generated by Django 5.1.4 on 2025-01-14 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_rename_clusterresourcequota_quota'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quota',
            unique_together={('zone', 'project')},
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=64)),
                ('node_ip', models.GenericIPAddressField()),
                ('node_ib_ip', models.GenericIPAddressField()),
                ('node_external_ip', models.GenericIPAddressField()),
                ('node_status', models.BooleanField(default=False)),
                ('node_cpu', models.IntegerField(default=0)),
                ('node_gpu', models.IntegerField(default=0)),
                ('node_mem', models.IntegerField(default=0)),
                ('cluster_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cloud.clusterprovider')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cloud.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservePlan',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserve_cpu', models.IntegerField(default=0)),
                ('reserve_gpu', models.IntegerField(default=0)),
                ('reserve_mem', models.IntegerField(default=0)),
                ('reserve_start', models.DateTimeField()),
                ('reserve_end', models.DateTimeField()),
                ('reserve_status', models.BooleanField(default=False)),
                ('reserve_reason', models.TextField(default='no reason')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_plan', to='project.project')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_plan', to='cloud.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
