# Generated by Django 5.1.5 on 2025-01-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0009_delete_clustercapacity'),
        ('project', '0006_project_private'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quota',
            new_name='ComputeQuota',
        ),
    ]
