x-config: &config
  # (REQUIRED) Replace '?' with '-' followed by a 50 character random string.
  # You can generate one at https://djecrety.ir/ or by running:
  #   echo $(cat /dev/urandom | LC_CTYPE=C tr -dc 'a-zA-Z0-9' | head -c 50)


services:
  nephele:
    build: .
    image: nephele:latest
    depends_on:
      - db
      - broker
    command:
      - uv
      - run
      - --
      - manage.py
      - runserver
      - 0.0.0.0:8000
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/
        - action: rebuild
          path: pyproject.toml
    volumes:
      - ./nephele:/opt/nephele/nephele:ro
      - ./apps:/opt/nephele/apps:ro
      - ./manage.py:/opt/nephele/manage.py:ro
    environment:
      - DATABASES__DEFAULT__HOST=db
    ports:
      - 8000:8000
  db:
    image: ${ARM:+arm64v8/}postgres:17
    shm_size: 128mb
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nephele
    ports:
      - 5432:5432

  adminer:
    image: ${ARM:+arm64v8/}adminer:4
    restart: always
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
      - ADMINER_DEFAULT_DB_HOST=db
      - ADMINER_DEFAULT_DB_NAME=nephele
    ports:
      - 8080:8080

  broker:
    image: ${ARM:+arm64v8/}rabbitmq:4-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672

  mailhog:
    image: richarvey/mailhog:1.3-linux-${IMG_ARCH:-amd64}
    ports:
      - 2525:1025
      - 8025:8025
  mathesar:
    image: mathesar/mathesar:latest
    depends_on:
      - db
    healthcheck:
      test: curl -f http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 5s
    expose:
      - "8000"
    # Uncomment the following if not using caddy
    ports:
      - 8083:8000
