services:
  nephele:
    build: .
    image: nephele:latest
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/
        - action: rebuild
          path: package.json
  db:
    image: ${ARM:+arm64v8/}postgres:12-alpine3.20

    shm_size: 128mb
    # volumes:
    #   - ./.docker/postgresql:/var/lib/postgresql/
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nephele
    ports:
      - 5432:5432

  adminer:
    image: ${ARM:+arm64v8/}adminer:4
    restart: always
    ports:
      - 8080:8080

  broker:
    image: ${ARM:+arm64v8/}rabbitmq:4-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672

  mailhog:
    image: richarvey/mailhog:1.3-linux-${IMG_ARCH:-amd64}
    ports:
      - 2525:1025
      - 8025:8025
