[project]
name = "nephele"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "celery>=5.4.0",
    "cryptography>=44.0.0",
    "django>=5.1.4",
    "pymysql>=1.1.1",
]

[tool.uv]
dev-dependencies = [
    "celery-types>=0.22.0",
    "django-types>=0.20.0",
    "django-stubs[compatible-mypy]>=5.1.1",
    "django-fake-model>=0.1.4",
]
