# Generated by Django 5.1.5 on 2025-01-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_deleted_at'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='css',
        ),
        migrations.RemoveField(
            model_name='template',
            name='html',
        ),
        migrations.RemoveField(
            model_name='template',
            name='js',
        ),
        migrations.AddField(
            model_name='template',
            name='cmd',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='cpu_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='cpu_request',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='entrypoint',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='env_vars',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='gpu_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='gpu_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='mem_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='mem_request',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='node_requested',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='project',
            field=models.ForeignKey(db_comment='All task template should belong to a project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
        migrations.AddField(
            model_name='template',
            name='selectors',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='template',
            name='storage_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='template',
            name='storage_request',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='template',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(db_comment='Description of the task template'),
        ),
    ]
