# Generated by Django 5.1.5 on 2025-01-20 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadType',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_file', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, db_comment='Description of the task template', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='workload_type',
            field=models.ForeignKey(db_comment='All task template should against one workload type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='task.workloadtype'),
        ),
    ]
