# Generated by Django 5.1.5 on 2025-01-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_workloadtype_alter_template_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='work_dir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='cmd',
            field=models.JSONField(default=['echo', '"Hello, World!"']),
        ),
    ]
