# Generated by Django 5.1.5 on 2025-01-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_template_work_dir_alter_template_cmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='cmd',
            field=models.JSONField(default=list),
        ),
    ]
