# Generated by Django 5.1.5 on 2025-01-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_template_cmd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spec',
            old_name='description',
            new_name='note',
        ),
    ]
