# Generated by Django 5.1.5 on 2025-01-21 02:48

import apps.task.models
import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_rename_description_spec_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='artifacts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='cmd',
            field=models.JSONField(default=apps.task.models.Template._default_cmd),
        ),
        migrations.AlterField(
            model_name='template',
            name='env_vars',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='selectors',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='BatchTask',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('spec', models.ForeignKey(db_comment='All task should against one task spec', on_delete=django.db.models.deletion.CASCADE, to='task.spec')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.template')),
            ],
            options={
                'abstract': False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
