# Generated by Django 5.1.5 on 2025-01-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprojectnamespace_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectnamespace',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
