# Generated by Django 5.1.5 on 2025-01-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprojectnamespace_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectnamespace',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
