# Generated by Django 5.1.5 on 2025-01-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
