# Generated by Django 5.1.4 on 2025-01-14 08:39

import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('default_mount', models.CharField(max_length=255)),
                ('path', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('name', models.Value('-'), django.db.models.functions.comparison.Cast('id', models.CharField())), output_field=models.CharField(max_length=100))),
                ('limit_size', models.IntegerField(default=0)),
                ('used_size', models.IntegerField(default=0)),
                ('access_level', models.IntegerField(default=0)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='storage.quota')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.layout')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mount_path', models.CharField(blank=True, max_length=255, null=True)),
                ('readonly', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to='data.dataset')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to='data.layout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
