# Generated by Django 5.1.4 on 2025-01-14 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud', '0007_alter_clustercapacity_zone'),
        ('data', '0001_initial'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='quota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='storage.quota'),
        ),
        migrations.AddField(
            model_name='layout',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.layout'),
        ),
        migrations.AddField(
            model_name='layout',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.zone'),
        ),
        migrations.AddField(
            model_name='mount',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to='data.dataset'),
        ),
        migrations.AddField(
            model_name='mount',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mounts', to='data.layout'),
        ),
    ]
