# Generated by Django 5.1.5 on 2025-01-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_layoutv2_layoutwithtn_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LayoutWithTN',
        ),
    ]
