# Generated by Django 5.1.5 on 2025-01-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_class_deleted_at_alter_quota_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='capacity',
            field=models.IntegerField(db_column='max capacity of storage service', default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='capacity_inodes',
            field=models.IntegerField(db_column='max capacity of inodes', default=0),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(db_comment='Name of the storage class', max_length=255),
        ),
    ]
