# Generated by Django 5.1.5 on 2025-01-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_class_api_endpoint_class_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='credentials',
            field=models.CharField(),
        ),
    ]
