# Generated by Django 5.1.5 on 2025-01-27 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_dataset_deleted_at_alter_layout_deleted_at_and_more'),
        ('project', '0006_project_private'),
        ('storage', '0005_alter_class_credentials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quota',
            new_name='StorageCapacity',
        ),
    ]
